spring:
  application:
    name: luoshu

  config:
    location: classpath:/
    additional-location: file:${LUOSHU_HOME}/config/
    name: luoshu
server:
  port: 9999
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
logging:
  config: classpath:logback-spring.xml
luoshu:
  webapp:
    path: ${LUOSHU_HOME}/luoshu-ui/
  plugin:
    root-dir: ${LUOSHU_HOME}/plugins/